- name: nginx restart
  service:
    name: nginx
    state: restarted
  ignore_errors: yes


- name: postfix restart
  service:
    name: postfix
    state: restarted
  ignore_errors: yes

- name: dovecot restart
  service:
    name: dovecot
    state: restarted
  ignore_errors: yes